<?php
namespace RDR\V2\HeadlessCMS\Portal;

use RDR\V2\HeadlessCMS\PostTypes;
use RDR\V2\HeadlessCMS\Settings as CoreSettings;
use RDR\V2\HeadlessCMS\Meta;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class About extends ContentModule {
    private $settings;
    public function __construct(CoreSettings $settings){$this->settings=$settings;}
    public function render(){if(!current_user_can('edit_posts'))Shell::simple_error(403,'Access denied','You do not have permission to manage About content.');$errors=array();$submitted=array();if('POST'===$_SERVER['REQUEST_METHOD']){$result=$this->save();if(!empty($result['redirect'])){wp_safe_redirect($result['redirect']);exit;}$errors=$result['errors'];$submitted=$result['submitted'];}$value=$submitted&&isset($submitted['about'])&&is_array($submitted['about'])?$submitted['about']:$this->settings->about();ob_start();?>
    <?php echo $this->errors_html($errors); ?><form method="post" class="rdr-form rdr-editor-form" data-rdr-unsaved><?php wp_nonce_field('rdr_portal_about_save','rdr_portal_nonce'); ?>
    <section class="rdr-card"><h2>About Content</h2><?php echo $this->textarea('about[intro]','Introduction',$value['intro']??'',5); ?><?php echo $this->textarea('about[story]','Professional Story',$value['story']??'',10); ?><?php echo $this->list_repeater_option('about[pillars]','Pillars',$value['pillars']??array()); ?><?php echo $this->list_repeater_option('about[principles]','Working Principles',$value['principles']??array()); ?><?php echo $this->list_repeater_option('about[expectations]','Client Expectations',$value['expectations']??array()); ?><?php echo $this->textarea('about[personal_note]','Personal / Professional Note',$value['personal_note']??'',6); ?></section>
    <section class="rdr-card"><h2>Portrait & Relationships</h2><?php echo Support::media_field('about[portrait_media_id]','Portrait',$value['portrait_media_id']??0); ?><div class="rdr-form-grid"><div class="rdr-field"><label>Featured Projects</label><?php echo Support::post_multiselect('about[featured_project_ids]',PostTypes::PROJECT,$value['featured_project_ids']??array()); ?></div><div class="rdr-field"><label>Featured Services</label><?php echo Support::post_multiselect('about[featured_service_ids]',PostTypes::SERVICE,$value['featured_service_ids']??array()); ?></div><div class="rdr-field"><label>Featured Reviews</label><?php echo Support::post_multiselect('about[featured_review_ids]',PostTypes::REVIEW,$value['featured_review_ids']??array()); ?></div></div><p class="rdr-help">Relationships store record IDs only; full related content is not duplicated into About.</p></section>
    <div class="rdr-sticky-actions"><button class="rdr-button rdr-button-primary" type="submit" data-rdr-save>Save About</button><span class="rdr-save-state" data-rdr-save-state aria-live="polite"></span></div></form>
    <?php $content=ob_get_clean();Shell::render('About','about',$content,array('subtitle'=>'Manage the single structured About content source.'));}
    private function list_repeater_option($name,$label,$items){$items=is_array($items)?$items:array();if(!$items)$items=array('');ob_start();?><div class="rdr-field rdr-repeater" data-rdr-repeater="list" data-name="<?php echo esc_attr($name); ?>[]"><label><?php echo esc_html($label); ?></label><div data-rdr-repeater-rows><?php foreach($items as $item):?><div class="rdr-repeater-row"><input type="text" name="<?php echo esc_attr($name); ?>[]" value="<?php echo esc_attr($item); ?>"><div class="rdr-row-actions"><button type="button" class="rdr-button rdr-button-quiet" data-rdr-up>↑</button><button type="button" class="rdr-button rdr-button-quiet" data-rdr-down>↓</button><button type="button" class="rdr-button rdr-button-quiet" data-rdr-remove>Remove</button></div></div><?php endforeach;?></div><button type="button" class="rdr-button rdr-button-secondary" data-rdr-add>Add item</button></div><?php return ob_get_clean();}
    private function save(){ $submitted=wp_unslash($_POST);$errors=array();if(!isset($_POST['rdr_portal_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['rdr_portal_nonce'])),'rdr_portal_about_save'))$errors[]='Security check failed. Reload and try again.';if(!current_user_can('edit_posts'))$errors[]='You do not have permission to save About content.';$input=isset($submitted['about'])&&is_array($submitted['about'])?$submitted['about']:array();$input['featured_project_ids']=Support::validate_relation_ids($input['featured_project_ids']??array(),PostTypes::PROJECT);$input['featured_service_ids']=Support::validate_relation_ids($input['featured_service_ids']??array(),PostTypes::SERVICE);$input['featured_review_ids']=Support::validate_relation_ids($input['featured_review_ids']??array(),PostTypes::REVIEW);if($errors)return array('errors'=>$errors,'submitted'=>$submitted);$clean=$this->settings->sanitize_about($input);update_option(CoreSettings::ABOUT_OPTION,$clean,false);return array('redirect'=>Support::url('about').'?rdr_notice=saved');}
}
