<?php
namespace RDR\V2\HeadlessCMS\Portal;

use RDR\V2\HeadlessCMS\Meta;
use RDR\V2\HeadlessCMS\PostTypes;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Reviews extends ContentModule {
    public function list_page() {
        $search=isset($_GET['s'])?sanitize_text_field(wp_unslash($_GET['s'])):'';$paged=max(1,isset($_GET['paged'])?absint($_GET['paged']):1);
        $query=new \WP_Query(array('post_type'=>PostTypes::REVIEW,'post_status'=>array('publish','draft','pending','private'),'posts_per_page'=>20,'paged'=>$paged,'s'=>$search,'orderby'=>'modified','order'=>'DESC'));
        ob_start(); ?>
        <section class="rdr-card"><form method="get" action="<?php echo esc_url(Support::url('reviews')); ?>" class="rdr-filters"><div class="rdr-field"><label for="rdr-review-search">Search</label><input id="rdr-review-search" name="s" value="<?php echo esc_attr($search); ?>" placeholder="Reviewer or review content"></div><button class="rdr-button rdr-button-secondary" type="submit">Search</button></form></section>
        <section class="rdr-card rdr-table-card"><?php if($query->have_posts()): ?><div class="rdr-table-wrap"><table class="rdr-table"><thead><tr><th>Reviewer</th><th>Rating</th><th>Source</th><th>Service</th><th>Project</th><th>Featured</th><th>Publication</th><th>Order</th><th>Actions</th></tr></thead><tbody><?php foreach($query->posts as $post):$sid=absint(get_post_meta($post->ID,'_rdr_related_service_id',true));$pid=absint(get_post_meta($post->ID,'_rdr_related_project_id',true));$s=$sid?get_post($sid):null;$p=$pid?get_post($pid):null;$rating=(float)get_post_meta($post->ID,'_rdr_rating',true);?><tr><td><strong><?php echo esc_html(get_post_meta($post->ID,'_rdr_reviewer_name',true)?:$post->post_title); ?></strong></td><td><?php echo $rating>0?esc_html(number_format_i18n($rating,1)):'—'; ?></td><td><?php echo esc_html(get_post_meta($post->ID,'_rdr_source',true)?:'—'); ?></td><td><?php echo esc_html($s instanceof \WP_Post?$s->post_title:'—'); ?></td><td><?php echo esc_html($p instanceof \WP_Post?$p->post_title:'—'); ?></td><td><?php echo get_post_meta($post->ID,'_rdr_featured',true)?'Yes':'No'; ?></td><td><span class="rdr-badge"><?php echo esc_html(Support::portal_state_options()[Support::current_portal_state($post)]); ?></span></td><td><?php echo absint(get_post_meta($post->ID,'_rdr_display_order',true)); ?></td><td><a class="rdr-link" href="<?php echo esc_url(Support::url('reviews/edit/'.$post->ID)); ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div><?php else:?><div class="rdr-empty"><h2>No reviews found</h2><p>Add a verified review record when source information is available.</p></div><?php endif; ?></section>
        <?php $content=ob_get_clean();$actions='<a class="rdr-button rdr-button-primary" href="'.esc_url(Support::url('reviews/add')).'">Add Review</a>';Shell::render('Reviews','reviews',$content,array('subtitle'=>'Manage verified review content and explicit relationships.','actions'=>$actions));
    }
    public function add_page(){ $this->form_page(null); }
    public function edit_page($id){$post=get_post(absint($id));if(!$post instanceof \WP_Post||PostTypes::REVIEW!==$post->post_type)Shell::simple_error(404,'Review not found','The requested Review does not exist or has the wrong content type.');if(!current_user_can('edit_post',$post->ID))Shell::simple_error(403,'Access denied','You do not have permission to edit this Review.');$this->form_page($post);}
    private function form_page($post){$is_edit=$post instanceof \WP_Post;$errors=array();$field_errors=array();$submitted=array();if('POST'===$_SERVER['REQUEST_METHOD']){$result=$this->handle_save($post);if(!empty($result['redirect'])){wp_safe_redirect($result['redirect']);exit;}$errors=$result['errors'];$field_errors=$result['field_errors'];$submitted=$result['submitted'];}$meta=$submitted&&isset($submitted['meta'])&&is_array($submitted['meta'])?$submitted['meta']:array();$state=$submitted?(isset($submitted['portal_state'])?$submitted['portal_state']:'draft'):($is_edit?Support::current_portal_state($post):'draft');ob_start(); ?>
        <?php echo $this->errors_html($errors); ?><form method="post" class="rdr-form rdr-editor-form" data-rdr-unsaved><?php wp_nonce_field('rdr_portal_review_save','rdr_portal_nonce'); ?>
        <section class="rdr-card"><h2>Review Details</h2><div class="rdr-form-grid"><?php echo $this->field('meta[_rdr_reviewer_name]','Reviewer Display Name',$this->meta($post,'_rdr_reviewer_name',$meta),'text',true,'',isset($field_errors['reviewer'])?$field_errors['reviewer']:''); ?><?php echo $this->field('meta[_rdr_rating]','Rating (optional, 1–5)',$this->meta($post,'_rdr_rating',$meta),'number',false,'Leave blank if no verified rating exists.',isset($field_errors['rating'])?$field_errors['rating']:''); ?><?php echo $this->field('meta[_rdr_source]','Source',$this->meta($post,'_rdr_source',$meta)); ?><?php echo $this->field('meta[_rdr_source_url]','Source URL',$this->meta($post,'_rdr_source_url',$meta),'url'); ?><?php echo $this->field('meta[_rdr_context]','Context',$this->meta($post,'_rdr_context',$meta)); ?><?php echo $this->field('meta[_rdr_country]','Verified Country / Location',$this->meta($post,'_rdr_country',$meta)); ?><?php echo $this->field('meta[_rdr_review_date]','Verified Review Date',$this->meta($post,'_rdr_review_date',$meta),'date',false,'Optional; do not invent a date.'); ?><?php echo $this->field('meta[_rdr_display_order]','Display Order',$this->meta($post,'_rdr_display_order',$meta),'number'); ?></div><?php echo $this->textarea('meta[_rdr_review_text]','Review Text / Accepted Public Summary',$this->meta($post,'_rdr_review_text',$meta),7,true,'',isset($field_errors['text'])?$field_errors['text']:''); ?><?php echo $this->checkbox('meta[_rdr_featured]','Featured Review',$this->meta($post,'_rdr_featured',$meta)); ?><?php echo $this->select('portal_state','Publishing State',Support::portal_state_options(),$state); ?></section>
        <section class="rdr-card"><h2>Relationships</h2><p class="rdr-help">Relationships are explicit and optional. They are never inferred from review wording.</p><div class="rdr-form-grid"><?php echo $this->relation_select('meta[_rdr_related_service_id]','Related Service',PostTypes::SERVICE,$this->meta($post,'_rdr_related_service_id',$meta)); ?><?php echo $this->relation_select('meta[_rdr_related_project_id]','Related Project',PostTypes::PROJECT,$this->meta($post,'_rdr_related_project_id',$meta)); ?></div></section>
        <div class="rdr-sticky-actions"><a class="rdr-button rdr-button-secondary" href="<?php echo esc_url(Support::url('reviews')); ?>">Cancel</a><button class="rdr-button rdr-button-primary" type="submit" data-rdr-save><?php echo $is_edit?'Save Review':'Create Review'; ?></button><span class="rdr-save-state" data-rdr-save-state aria-live="polite"></span></div></form>
        <?php $content=ob_get_clean();Shell::render($is_edit?'Edit Review':'Add Review','reviews',$content,array('breadcrumbs'=>array(array('label'=>'Reviews','url'=>Support::url('reviews')),array('label'=>$is_edit?'Edit':'Add'))));}
    private function handle_save($post){$is_edit=$post instanceof \WP_Post;$submitted=wp_unslash($_POST);$errors=array();$field_errors=array();if(!isset($_POST['rdr_portal_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['rdr_portal_nonce'])),'rdr_portal_review_save'))$errors[]='Security check failed. Reload and try again.';if($is_edit?!current_user_can('edit_post',$post->ID):!current_user_can('edit_posts'))$errors[]='You do not have permission to save this Review.';$meta=isset($submitted['meta'])&&is_array($submitted['meta'])?$submitted['meta']:array();$reviewer=isset($meta['_rdr_reviewer_name'])?sanitize_text_field($meta['_rdr_reviewer_name']):'';$text=isset($meta['_rdr_review_text'])?sanitize_textarea_field($meta['_rdr_review_text']):'';if(''===$reviewer){$errors[]='Reviewer display name is required.';$field_errors['reviewer']='Enter the reviewer display name or username.';}if(''===$text){$errors[]='Review text is required.';$field_errors['text']='Enter the verified review text or accepted public summary.';}$rating=isset($meta['_rdr_rating'])?$meta['_rdr_rating']:'';if(''!==$rating&&null!==$rating){$r=(float)$rating;if($r<1||$r>5){$errors[]='Rating must be between 1 and 5 or left blank.';$field_errors['rating']='Use a verified value from 1 to 5.';}}$state=isset($submitted['portal_state'])?sanitize_key($submitted['portal_state']):'draft';if(!array_key_exists($state,Support::portal_state_options()))$errors[]='Publishing state is invalid.';$sid=Support::validate_relation(isset($meta['_rdr_related_service_id'])?$meta['_rdr_related_service_id']:0,PostTypes::SERVICE,true);$pid=Support::validate_relation(isset($meta['_rdr_related_project_id'])?$meta['_rdr_related_project_id']:0,PostTypes::PROJECT,true);if(false===$sid)$errors[]='Related Service is invalid.';if(false===$pid)$errors[]='Related Project is invalid.';if($errors)return array('errors'=>$errors,'field_errors'=>$field_errors,'submitted'=>$submitted);$mapped=Support::state_to_storage($state);$title=$reviewer;$postarr=array('post_type'=>PostTypes::REVIEW,'post_title'=>$title,'post_status'=>$mapped['post_status']);if($is_edit){$postarr['ID']=$post->ID;$id=wp_update_post($postarr,true);}else{$id=wp_insert_post($postarr,true);}if(is_wp_error($id))return array('errors'=>array('WordPress could not save the Review: '.$id->get_error_message()),'field_errors'=>array(),'submitted'=>$submitted);$meta['_rdr_related_service_id']=$sid;$meta['_rdr_related_project_id']=$pid;$meta[Meta::PUBLICATION_STATE]=$mapped['rdr_state'];Support::save_meta_fields($id,Meta::review_fields(),$meta);return array('redirect'=>Support::url('reviews/edit/'.$id).'?rdr_notice='.($is_edit?'saved':'created'));}
}
